# Generated by Django 5.0.2 on 2024-02-09 11:41

import projects.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[projects.validators.validate_github]),
        ),
        migrations.AlterField(
            model_name='project',
            name='kaggle',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[projects.validators.validate_kaggle]),
        ),
        migrations.AlterField(
            model_name='project',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[projects.validators.validate_website]),
        ),
    ]
