# Generated by Django 5.0.2 on 2024-02-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_github_alter_project_kaggle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='project-img.webp', upload_to='images/'),
        ),
    ]
